# Generated by Django 3.2.12 on 2022-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('score1', models.BooleanField()),
                ('score2', models.BooleanField()),
                ('score3', models.BooleanField()),
                ('score4', models.BooleanField()),
                ('score5', models.BooleanField()),
                ('score6', models.BooleanField()),
            ],
        ),
    ]
