# Generated by Django 3.2.12 on 2022-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='normalized_title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
